### ISSUE TITLE
cannot send/receive msg 

### ISSUE THREAD

**Issue by faysal515** [abdurrahmanekr/peanut#3]
After upgrading the react native version, I was able to run the project and connect through websocket transport. But message receive callback isn't firing as well as msg is not getting sent properly

**Comment by abdurrahmanekr** [comment]
Can you see the Request in network list? What did you send by data?

**Comment by faysal515** [comment]
this part is for receiving msg. I opened adium to log-in to the other account user and messaged the logged-in user. didn't fire this event
```js
client.on('session:started', () => {
			self.addLog('connected');
			client.on('message', msg => {
				console.log(msg);
				self.addLog(msg.toString());
			});
		});
```

**Comment by faysal515** [comment]
nevermind, its working now, had some class lever variable declaration problem
